dino:
  out_dim: 65536  # Dimensionality of DINO head
  local_crops_n: 8
  global_crops_n: 2
  warmup_teacher_temp: 0.04
  teacher_temp: 0.04
  warmup_teacher_temp_epochs: 5
  student_temp: 0.1
  center_momentum: 0.9

model:
  name: dino
  arch: vit_base
  patch_size: 16
  drop_path_rate: 0.1
  remove_head: 0
  mlp: "2048-512"
  mlp_coeff: 1.0
  patch_keep: 1.0
  fc: 0
  proj_relu: 0

training:
  eval_only: 0
  eval_freq: 100
  batch_size: 512
  num_crops: 1
  optimizer: adamw  # Options: ['sgd', 'adamw', 'lars']
  momentum: 0.9
  weight_decay: 4e-5
  epochs: 30
  base_lr: 0.0005
  end_lr_ratio: 0.001
  label_smoothing: 0.0
  distributed: 0
  clip_grad: 0.0
  use_ssl: 1
  loss: dino
  train_probes_only: 0
  mixup: 0.0

validation:
  batch_size: 25
  resolution: 224

logging:
  wandb: True
  wandb_project: "mixing-ssl"
  folder: "logs/test1/"  # Required, specify log folder
  log_level: 2
  checkpoint_freq: 20

distributed:
  use_submitit: 0
  world_size: 1
  ngpus: 4
  nodes: 1
  comment: ""
  timeout: 2800
  partition: learnlab
  address: localhost
  port: 58492